# Generated by Django 4.1.3 on 2022-11-28 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter product description', verbose_name='Product Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Enter product discount price', verbose_name='Product discount price'),
        ),
    ]
