# Generated by Django 4.1.3 on 2022-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_about_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(help_text='Enter product description', max_length=500, verbose_name='Product Description'),
        ),
    ]
