# Generated by Django 4.1.3 on 2022-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(blank=True, help_text='Enter product description', max_length=500, null=True, verbose_name='Product Description'),
        ),
    ]
