# Generated by Django 4.1.3 on 2022-11-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Choose category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Category'),
        ),
    ]
