# Generated by Django 4.1.3 on 2022-11-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter client name', max_length=100, null=True, verbose_name='Client name')),
                ('username', models.CharField(blank=True, help_text='Enter client username', max_length=100, null=True, verbose_name='Client username')),
                ('telegram_id', models.CharField(help_text='Enter telegram ID', max_length=30, unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(default='uz', help_text='Enter client system language', max_length=10, verbose_name='Client System Language')),
                ('phone', models.CharField(blank=True, help_text='Enter client phone', max_length=100, null=True, verbose_name='Client Phone Number')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client ',
                'verbose_name_plural': 'Clients ',
                'db_table': 'Cleints',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(help_text='Enter client latitude', max_length=50, verbose_name='Client latitude')),
                ('longitude', models.CharField(help_text='Enter client longitude', max_length=50, verbose_name='Client longitude')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', to_field='telegram_id')),
            ],
            options={
                'verbose_name': 'Address ',
                'verbose_name_plural': 'Addresses ',
                'db_table': 'Address',
            },
        ),
    ]
