# Generated by Django 4.1.3 on 2022-11-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address ', 'verbose_name_plural': 'Address '},
        ),
    ]
